# Generated by Django 6.0.4 on 2026-05-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("parsed_data", models.JSONField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
