# Generated by Django 6.0.3 on 2026-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tax_invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('credit_note', 'Credit Note'), ('tax_invoice_qic', 'Tax Invoice - QIC'), ('tax_invoice_dni', 'Tax Invoice - DNI'), ('tax_invoice_adamjee', 'Tax Invoice - Adamjee'), ('tax_invoice_sharjah', 'Tax Invoice - Sharjah'), ('tax_invoice_methaq', 'Tax Invoice - Methaq'), ('tax_invoice_arabia', 'Tax Invoice - Arabia'), ('tax_invoice_rak', 'Tax Invoice - RAK'), ('tax_invoice_nia', 'Tax Invoice - NIA'), ('tax_invoice_alliance', 'Tax Invoice - Alliance'), ('tax_invoice_watania', 'Tax Invoice - Watania'), ('tax_invoice_alsagr', 'Tax Invoice - Al Sagr'), ('tax_invoice_fidelity', 'Tax Invoice - Fidelity'), ('invoice', 'Generic Invoice'), ('unknown', 'Unknown')], default='unknown', max_length=100),
        ),
    ]
